title: "Ecomusée de Malume"
description: "Projet d’écomusée ferroviaire de Malume (Eséka, Cameroun) : patrimoine, mémoire et nature."
theme: null

remote_theme: just-the-docs/just-the-docs

# GitHub Pages (compte: Ngue-Um, dépôt: ecomusee-malume)
url: "https://ngue-um.github.io"
baseurl: "/ecomusee-malume"

search_enabled: true

just_the_docs:
  nav_sort: case_insensitive
  nav_external_links_new_tab: true
  color_scheme: ecomusee

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

encoding: "utf-8"
markdown: kramdown

exclude:
  - README.md
